export declare const PERMISSIONS: {
    readonly USERS_READ: "users:read";
    readonly USERS_CREATE: "users:create";
    readonly USERS_UPDATE: "users:update";
    readonly USERS_DELETE: "users:delete";
    readonly ROLES_READ: "roles:read";
    readonly ROLES_CREATE: "roles:create";
    readonly ROLES_UPDATE: "roles:update";
    readonly ROLES_DELETE: "roles:delete";
    readonly PERMISSIONS_READ: "permissions:read";
    readonly PERMISSIONS_CREATE: "permissions:create";
    readonly PERMISSIONS_UPDATE: "permissions:update";
    readonly PERMISSIONS_DELETE: "permissions:delete";
    readonly HR_EMPLOYEES_READ: "hr:employees:read";
    readonly HR_EMPLOYEES_CREATE: "hr:employees:create";
    readonly HR_EMPLOYEES_UPDATE: "hr:employees:update";
    readonly HR_EMPLOYEES_DELETE: "hr:employees:delete";
    readonly HR_ATTENDANCE_READ: "hr:attendance:read";
    readonly HR_ATTENDANCE_CREATE: "hr:attendance:create";
    readonly HR_ATTENDANCE_UPDATE: "hr:attendance:update";
    readonly HR_LEAVES_READ: "hr:leaves:read";
    readonly HR_LEAVES_APPROVE: "hr:leaves:approve";
    readonly HR_LEAVES_REJECT: "hr:leaves:reject";
    readonly HR_PAYROLL_READ: "hr:payroll:read";
    readonly HR_PAYROLL_CREATE: "hr:payroll:create";
    readonly HR_PAYROLL_UPDATE: "hr:payroll:update";
    readonly MARKETING_CAMPAIGNS_READ: "marketing:campaigns:read";
    readonly MARKETING_CAMPAIGNS_CREATE: "marketing:campaigns:create";
    readonly MARKETING_CAMPAIGNS_UPDATE: "marketing:campaigns:update";
    readonly MARKETING_CAMPAIGNS_DELETE: "marketing:campaigns:delete";
    readonly MARKETING_CAMPAIGNS_PUBLISH: "marketing:campaigns:publish";
    readonly MARKETING_TEMPLATES_READ: "marketing:templates:read";
    readonly MARKETING_TEMPLATES_CREATE: "marketing:templates:create";
    readonly MARKETING_TEMPLATES_UPDATE: "marketing:templates:update";
    readonly MARKETING_TEMPLATES_DELETE: "marketing:templates:delete";
    readonly MARKETING_ANALYTICS_READ: "marketing:analytics:read";
    readonly POS_TRANSACTIONS_READ: "pos:transactions:read";
    readonly POS_TRANSACTIONS_CREATE: "pos:transactions:create";
    readonly POS_TRANSACTIONS_UPDATE: "pos:transactions:update";
    readonly POS_TRANSACTIONS_DELETE: "pos:transactions:delete";
    readonly POS_PRODUCTS_READ: "pos:products:read";
    readonly POS_CUSTOMERS_READ: "pos:customers:read";
    readonly POS_CUSTOMERS_CREATE: "pos:customers:create";
    readonly POS_CUSTOMERS_UPDATE: "pos:customers:update";
    readonly POS_REPORTS_READ: "pos:reports:read";
    readonly INVENTORY_PRODUCTS_READ: "inventory:products:read";
    readonly INVENTORY_PRODUCTS_CREATE: "inventory:products:create";
    readonly INVENTORY_PRODUCTS_UPDATE: "inventory:products:update";
    readonly INVENTORY_PRODUCTS_DELETE: "inventory:products:delete";
    readonly INVENTORY_STOCK_READ: "inventory:stock:read";
    readonly INVENTORY_STOCK_UPDATE: "inventory:stock:update";
    readonly INVENTORY_CATEGORIES_READ: "inventory:categories:read";
    readonly INVENTORY_CATEGORIES_CREATE: "inventory:categories:create";
    readonly INVENTORY_CATEGORIES_UPDATE: "inventory:categories:update";
    readonly INVENTORY_CATEGORIES_DELETE: "inventory:categories:delete";
    readonly INVENTORY_REPORTS_READ: "inventory:reports:read";
    readonly SYSTEM_SETTINGS_READ: "system:settings:read";
    readonly SYSTEM_SETTINGS_UPDATE: "system:settings:update";
    readonly SYSTEM_AUDIT_READ: "system:audit:read";
    readonly SYSTEM_HEALTH_READ: "system:health:read";
};
export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS];
export declare const PERMISSION_DESCRIPTIONS: {
    readonly "users:read": "View user accounts";
    readonly "users:create": "Create new user accounts";
    readonly "users:update": "Update user account information";
    readonly "users:delete": "Delete user accounts";
    readonly "roles:read": "View roles and permissions";
    readonly "roles:create": "Create new roles";
    readonly "roles:update": "Update role information";
    readonly "roles:delete": "Delete roles";
    readonly "permissions:read": "View system permissions";
    readonly "permissions:create": "Create new permissions";
    readonly "permissions:update": "Update permission information";
    readonly "permissions:delete": "Delete permissions";
    readonly "hr:employees:read": "View employee information";
    readonly "hr:employees:create": "Create new employee records";
    readonly "hr:employees:update": "Update employee information";
    readonly "hr:employees:delete": "Delete employee records";
    readonly "hr:attendance:read": "View attendance records";
    readonly "hr:attendance:create": "Create attendance records";
    readonly "hr:attendance:update": "Update attendance records";
    readonly "hr:leaves:read": "View leave requests";
    readonly "hr:leaves:approve": "Approve leave requests";
    readonly "hr:leaves:reject": "Reject leave requests";
    readonly "hr:payroll:read": "View payroll information";
    readonly "hr:payroll:create": "Create payroll records";
    readonly "hr:payroll:update": "Update payroll records";
    readonly "marketing:campaigns:read": "View marketing campaigns";
    readonly "marketing:campaigns:create": "Create marketing campaigns";
    readonly "marketing:campaigns:update": "Update marketing campaigns";
    readonly "marketing:campaigns:delete": "Delete marketing campaigns";
    readonly "marketing:campaigns:publish": "Publish marketing campaigns";
    readonly "marketing:templates:read": "View marketing templates";
    readonly "marketing:templates:create": "Create marketing templates";
    readonly "marketing:templates:update": "Update marketing templates";
    readonly "marketing:templates:delete": "Delete marketing templates";
    readonly "marketing:analytics:read": "View marketing analytics";
    readonly "pos:transactions:read": "View POS transactions";
    readonly "pos:transactions:create": "Create POS transactions";
    readonly "pos:transactions:update": "Update POS transactions";
    readonly "pos:transactions:delete": "Cancel POS transactions";
    readonly "pos:products:read": "View products in POS";
    readonly "pos:customers:read": "View customer information";
    readonly "pos:customers:create": "Create customer records";
    readonly "pos:customers:update": "Update customer information";
    readonly "pos:reports:read": "View POS reports";
    readonly "inventory:products:read": "View inventory products";
    readonly "inventory:products:create": "Create inventory products";
    readonly "inventory:products:update": "Update inventory products";
    readonly "inventory:products:delete": "Delete inventory products";
    readonly "inventory:stock:read": "View stock levels";
    readonly "inventory:stock:update": "Update stock levels";
    readonly "inventory:categories:read": "View product categories";
    readonly "inventory:categories:create": "Create product categories";
    readonly "inventory:categories:update": "Update product categories";
    readonly "inventory:categories:delete": "Delete product categories";
    readonly "inventory:reports:read": "View inventory reports";
    readonly "system:settings:read": "View system settings";
    readonly "system:settings:update": "Update system settings";
    readonly "system:audit:read": "View audit logs";
    readonly "system:health:read": "View system health status";
};
//# sourceMappingURL=permissions.d.ts.map